version: '3.8'

services:
  bot:
    build: .
    container_name: cmsg-bot
    restart: always
    environment:
      DB_USER: postgres
      DB_PASSWORD: REMOVED
      DB_NAME: cmsg
      DB_HOST: db  # Имя сервиса базы данных из docker-compose
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: cmsg-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: REMOVED
      POSTGRES_DB: cmsg
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
